---
title: "Market simulator"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r load-packages, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(flexdashboard)
library(plotly)
library(shiny)
```

```{r load-data, message=FALSE}

# If we simplify any of the default data sets make sure it matches the gammas as well.

# number of Gamma rows -> number of Organization rows

# number of Gamma Cols -> number of Persona Rows


# Gammas of the "everything" model
gammas <- read_rds(
    here::here('data', 'public_political_social_charity_demo.rds')
  ) %>% 
  group_by(i, j) %>% 
  summarize(gamma_mean = mean(Gamma)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = j, values_from = gamma_mean) %>% 
  select(-i) %>% 
  t()

# Default configurations
prod_default <- read_csv(
    here::here('data', 'org_data_default.csv')
  )
seg_default <- read_csv(
    here::here('data', 'per_data_default.csv')
  )
```

```{r product-reactive-table}
# Assign level labels
prod_table <- data.frame(
  levels = c(
    # Brand
    "Amnesty International",
    "Greenpeace", 
    "Oxfam", 
    "Red Cross",
    # Lid Type
    "Environment", 
    "Human rights",
    "Refugee relief",
    # Size
    "Engages in financial transparency",
    # Color
    "Engages in financial accountability",
    # Material
    "Handful of wealthy private donors", 
    "Government grants",
    # Price
    "Criticized by government",
    "Under government crackdown"
  )
)

# Product configuration reactive element
prod_reactive <- reactive({
  # Product 1
  prod_table$prod1_value <- 0
  prod_table$prod1_value[prod_table$levels %in% input$prod1_prod] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_issue] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_fin_trans] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_fin_account] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_funding] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_host_gov] <- 1
    
  # Product 2
  prod_table$prod2_value <- 0
  prod_table$prod2_value[prod_table$levels %in% input$prod2_prod] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_issue] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_fin_trans] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_fin_account] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_funding] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_host_gov] <- 1
    
  # Product 3
  prod_table$prod3_value <- 0
  prod_table$prod3_value[prod_table$levels %in% input$prod3_prod] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_issue] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_fin_trans] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_fin_account] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_funding] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_host_gov] <- 1
    
  # Product 4
  prod_table$prod4_value <- 0
  prod_table$prod4_value[prod_table$levels %in% input$prod4_prod] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_issue] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_fin_trans] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_fin_account] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_funding] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_host_gov] <- 1
  prod_table
})
```

```{r segment-reactive-table}
# Assign covariate labels
seg_table <- data.frame(
  levels = c(
    # Intercept
    "Intercept",
    # Follow national news
    "Once a week",
    "At least once a day",
    # Follow international news
    "Sometimes",
    "Always",
    # Mediums to follow news
    "TV",
    "Print",
    "Online (not social media)",
    "Social media",
    "Radio",
    "Email newsletter",
    "News app",
    # Follow government and public affairs
    "Often", 
    # Traveled to a developing country
    "Traveled to a developing country", 
    # Liberal to Conservative
    "Somewhat liberal",
    "Slightly liberal",
    "Moderate",
    "Slightly conservative",
    "Somewhat conservative",
    "Extremely conservative",
    # Trust in political institutions
    "Very little trust in political institutions",
    "Little trust in political institutions",
    "Neutral trust in political institutions",
    "Some trust in political institutions",
    "A lot of trust in political institutions",
    "Complete trust in political institutions",
    # People should be more charitable
    "Disagree",
    "Somewhat disagree",
    "Neutral",
    "Somewhat agree",
    "Agree",
    "Strongly agree",
    # Religious attendance
    "Rarely attend",
    "Attend at least once a month",
    # Importance of religion
    "Important",
    # Religion
    "Protestant",
    "Christian Orthodox",
    "Jewish",
    "Muslim",
    "Sikh",
    "Hindu",
    "Buddhist",
    "Atheist",
    "Other religion",
    # Importance of trusting charities
    "Very unimportant",
    "Somewhat unimportant",
    "Neutral importance",
    "Somewhat important",
    "Very important",
    "Essential",
    # Trust in charities
    "Very little trust in charities",
    "Little trust in charities",
    "Neutral trust in charities",
    "Some trust in charities",
    "A lot of trust in charities",
    "Complete trust in charities",
    # Donation frequency
    "Donate at least once a month", 
    # Donated last year
    "$50-$99",
    "$100-$499",
    "$500-$999",
    "$1,000-$4,999",
    "$5,000-$9,999",
    "$10,000+",
    # Volunteered in past 12 months
    "Volunteered in past 12 months",
    # Volunteer frequency
    "Rarely volunteer",
    "Volunteer more than once a month, less than once a year",
    "Volunteer at least once a month",
    # History of activism
    "Personally involved",
    # History of family activism
    "Family involved",
    # Church or religious organization
    "Inactive church member",
    "Active church member",
    # Sport or recreational organization
    "Inactive sports or rec organization member",
    "Active sports or rec organization member", 
    # Art, music, or educational organization
    "Inactive art, music, or educational organization member",
    "Active art, music, or educational organization member",
    # Labor union
    "Inactive union member",
    "Active union member",
    # Political party
    "Inactive political party member",
    "Active political party member",
    # Environmental organization
    "Inactive environmental organization member",
    "Active environmental organization member",
    # Professional association
    "Inactive professional association member",
    "Active professional association member",
    # Humanitarian or charitable organization
    "Inactive humanitarian or charitable organization member",
    "Active humanitarian or charitable organization member",
    # Consumer organization
    "Inactive consumer organization member",
    "Active consumer organization member",
    # Other organization
    "Inactive member in another organization",
    "Active member in another organization",
    # Gender
    "Female",
    "Transgender",
    "Prefer not to say",
    "Other gender",
    # Marital status
    "Widowed",
    "Divorced",
    "Separated",
    "Never married",
    # Education
    "High school graduate", 
    "Some college",
    "2 year degree",
    "4 year degree",
    "Graduate or professional degree",
    "Doctorate",
    # Income
    "More than median of $61,372", 
    # Race
    "White", 
    "Black or African American", 
    "American Indian or Alaskan Native", 
    "Asian", 
    "Native Hawaiian or Pacific Islander",
    "Other race",
    # Age
    "More than median age of 36"
  )
)

# Segment configuration reactive element
seg_reactive <- reactive({
  # Segment 1
  seg_table$seg1_value <- 0
  seg_table$seg1_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_national_news] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_international_news] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_news_medium] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_follow_gov] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_travel_developing] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_political_pref] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_institution_trust] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_others_charitable] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_worship_attendance] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_religion_importance] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_religion] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_charity_importance] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_trust_in_charity] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_donation_frequency] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_donation_amount] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_volunteer_12] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_volunteer_frequency] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_personal_activism] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_family_activism] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_religious_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_sport_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_art_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_labor_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_political_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_environmental_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_professional_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_humanitarian_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_consumer_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_other_member] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_gender] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_marital_status] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_education] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_income] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_race] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$per1_age] <- 1
    
  # Segment 2
  seg_table$seg2_value <- 0
  seg_table$seg2_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_national_news] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_international_news] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_news_medium] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_follow_gov] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_travel_developing] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_political_pref] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_institution_trust] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_others_charitable] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_worship_attendance] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_religion_importance] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_religion] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_charity_importance] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_trust_in_charity] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_donation_frequency] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_donation_amount] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_volunteer_12] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_volunteer_frequency] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_personal_activism] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_family_activism] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_religious_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_sport_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_art_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_labor_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_political_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_environmental_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_professional_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_humanitarian_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_consumer_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_other_member] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_gender] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_marital_status] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_education] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_income] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_race] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$per2_age] <- 1
    
  # Segment 3
  seg_table$seg3_value <- 0
  seg_table$seg3_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_national_news] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_international_news] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_news_medium] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_follow_gov] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_travel_developing] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_political_pref] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_institution_trust] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_others_charitable] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_worship_attendance] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_religion_importance] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_religion] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_charity_importance] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_trust_in_charity] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_donation_frequency] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_donation_amount] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_volunteer_12] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_volunteer_frequency] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_personal_activism] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_family_activism] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_religious_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_sport_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_art_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_labor_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_political_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_environmental_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_professional_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_humanitarian_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_consumer_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_other_member] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_gender] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_marital_status] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_education] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_income] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_race] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$per3_age] <- 1
  seg_table
})
```

Market share
-------------------------------------------------

```{r compute-and-plot}
# Compute and render the market share plot
renderPlotly({
  prod_choice = prod_reactive()
  seg_choice = seg_reactive()
    
  # Segment 1 predicted betas
  per1_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,2])
  
  # Segment 1 expected utilities
  per1_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per1_betas))
  per1_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per1_betas))
  per1_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per1_betas))
  per1_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per1_betas))
  
  # Segment 1 market shares
  per1_share_denom <- sum(per1_prod1_exp, per1_prod2_exp, per1_prod3_exp, per1_prod4_exp)
  per1_prod1_share <- 100 * (per1_prod1_exp / per1_share_denom)
  per1_prod2_share <- 100 * (per1_prod2_exp / per1_share_denom)
  per1_prod3_share <- 100 * (per1_prod3_exp / per1_share_denom)
  per1_prod4_share <- 100 * (per1_prod4_exp / per1_share_denom)
  
  # Segment 2 predicted betas
  per2_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,3])
  
  # Segment 2 expected utilities
  per2_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per2_betas))
  per2_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per2_betas))
  per2_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per2_betas))
  per2_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per2_betas))
  
  # Segment 2 market shares
  per2_share_denom <- sum(per2_prod1_exp, per2_prod2_exp, per2_prod3_exp, per2_prod4_exp)
  per2_prod1_share <- 100 * (per2_prod1_exp / per2_share_denom)
  per2_prod2_share <- 100 * (per2_prod2_exp / per2_share_denom)
  per2_prod3_share <- 100 * (per2_prod3_exp / per2_share_denom)
  per2_prod4_share <- 100 * (per2_prod4_exp / per2_share_denom)
  
  # Segment 3 predicted betas
  per3_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,4])
  
  # Segment 3 expected utilities
  per3_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per3_betas))
  per3_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per3_betas))
  per3_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per3_betas))
  per3_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per3_betas))
  
  # Segment 3 market shares
  per3_share_denom <- sum(per3_prod1_exp, per3_prod2_exp, per3_prod3_exp, per3_prod4_exp)
  per3_prod1_share <- 100 * (per3_prod1_exp / per3_share_denom)
  per3_prod2_share <- 100 * (per3_prod2_exp / per3_share_denom)
  per3_prod3_share <- 100 * (per3_prod3_exp / per3_share_denom)
  per3_prod4_share <- 100 * (per3_prod4_exp / per3_share_denom)
  
  # Data for plotly
  plot_data <- data.frame(
    Value = c(
      # Segment 1
      per1_prod1_share, per1_prod2_share, per1_prod3_share, per1_prod4_share, 
      # Segment 2
      per2_prod1_share, per2_prod2_share, per2_prod3_share, per2_prod4_share,
      # Segment 3
      per3_prod1_share, per3_prod2_share, per3_prod3_share, per3_prod4_share
    ),
    Organization = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name),
    Segment = c(
      rep(input$per1_name, 4), 
      rep(input$per2_name, 4), 
      rep(input$per3_name, 4)
    )
  )
  
  ggplotly(
    plot_data %>% 
      # Factor Product and Segment with ordered=TRUE
      mutate(
        Organization = factor(
          Organization, 
          levels = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name), 
          ordered = TRUE
        ),
        Segment = factor(
          Segment, 
          levels = c(input$per1_name, input$per2_name, input$per3_name), 
          ordered = TRUE
        )
      ) %>% 
      ggplot(aes(y = Value, x = Organization, fill = Segment)) +
      geom_bar(position = "dodge", stat = "identity") +
      labs(x="", y = "Market Share") + 
      scale_fill_manual(values = c("#FFC30B", "#28a153", "#c23838")) +
      theme(
        legend.position = "right",
        panel.background = element_blank(),
        panel.grid.major.y = element_line(color = "#D3D3D3")
      )
    )
})

# Compute and render the market share as a table
renderTable({
  prod_choice = prod_reactive()
  per_choice = per_reactive()
    
  # Segment 1 predicted betas
  per1_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,2])
  
  # Segment 1 expected utilities
  per1_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per1_betas))
  per1_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per1_betas))
  per1_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per1_betas))
  per1_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per1_betas))
  
  # Segment 1 market shares
  per1_share_denom <- sum(per1_prod1_exp, per1_prod2_exp, per1_prod3_exp, per1_prod4_exp)
  per1_prod1_share <- 100 * (per1_prod1_exp / per1_share_denom)
  per1_prod2_share <- 100 * (per1_prod2_exp / per1_share_denom)
  per1_prod3_share <- 100 * (per1_prod3_exp / per1_share_denom)
  per1_prod4_share <- 100 * (per1_prod4_exp / per1_share_denom)
  
  # Segment 2 predicted betas
  per2_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,3])
  
  # Segment 2 expected utilities
  per2_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per2_betas))
  per2_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per2_betas))
  per2_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per2_betas))
  per2_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per2_betas))
  
  # Segment 2 market shares
  per2_share_denom <- sum(per2_prod1_exp, per2_prod2_exp, per2_prod3_exp, per2_prod4_exp)
  per2_prod1_share <- 100 * (per2_prod1_exp / per2_share_denom)
  per2_prod2_share <- 100 * (per2_prod2_exp / per2_share_denom)
  per2_prod3_share <- 100 * (per2_prod3_exp / per2_share_denom)
  per2_prod4_share <- 100 * (per2_prod4_exp / per2_share_denom)
  
  # Segment 3 predicted betas
  per3_betas <- as.matrix(gammas) %*% as.matrix(per_choice[,4])
  
  # Segment 3 expected utilities
  per3_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(per3_betas))
  per3_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(per3_betas))
  per3_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(per3_betas))
  per3_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(per3_betas))
  
  # Segment 3 market shares
  per3_share_denom <- sum(per3_prod1_exp, per3_prod2_exp, per3_prod3_exp, per3_prod4_exp)
  per3_prod1_share <- 100 * (per3_prod1_exp / per3_share_denom)
  per3_prod2_share <- 100 * (per3_prod2_exp / per3_share_denom)
  per3_prod3_share <- 100 * (per3_prod3_exp / per3_share_denom)
  per3_prod4_share <- 100 * (per3_prod4_exp / per3_share_denom)
  
  # Table
  data <- data.frame(
    Shares = c(
      # Segment 1
      per1_prod1_share, per1_prod2_share, per1_prod3_share, per1_prod4_share, 
      # Segment 2
      per2_prod1_share, per2_prod2_share, per2_prod3_share, per2_prod4_share,
      # Segment 3
      per3_prod1_share, per3_prod2_share, per3_prod3_share, per3_prod4_share
    ),
    Organization = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name),
    Segment = c(
      rep(input$per1_name, 4), 
      rep(input$per2_name, 4), 
      rep(input$per3_name, 4)
    )
  ) %>% 
    pivot_wider(names_from = Segment, values_from = Shares)
  
  data
})
```

Configurations
-------------------------------------------------

### Product 1

```{r org1-inputs}
# Naming
textInput(
  "prod1_name",
  label = "Product Name:",
  value = "Product 1",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Product
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_prod",
    label = "Product:",
    choice = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,2] == 1), 1]),
    width = "450px"
  )
})

# Issue area
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_issue", 
    label = "Issue Area:",
    choices = c("Emergency response", "Environment", "Human rights", "Refugee relief"),
    # selected = "Emergency response",
    selected = ifelse(
      sum(prod_data[5:7,2]) == 0, "Emergency response",
      as.character(prod_data[5:7,][which(prod_data[5:7,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial transparency
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_fin_trans",
    label = "Financial Transparency:",
    choices = c(
      "Doesn’t engage in financial transparency", 
      "Engages in financial transparency"
    ),
    # selected = "Engages in financial transparency",
    selected = ifelse(
      sum(prod_data[8,2]) == 0, "Doesn’t engage in financial transparency",
      as.character(prod_data[8,][which(prod_data[8,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial accountability
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_fin_account",
    label = "Financial Accountability:",
    choices = c(
      "Doesn’t engage in financial accountability", 
      "Engages in financial accountability"
    ),
    # selected = "Engages in financial accountability",
    selected = ifelse(
      sum(prod_data[9,2]) == 0, "Doesn’t engage in financial accountability",
      as.character(prod_data[9,][which(prod_data[9,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Funding sources
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_funding",
    label = "Funding Source:",
    choices = c(
      "Many small private donations", 
      "Handful of wealthy private donors", 
      "Government grants"
    ),
    # selected = "Many small private donations",
    selected = ifelse(
      sum(prod_data[10:11,2]) == 0, "Many small private donations",
      as.character(prod_data[10:11,][which(prod_data[10:11,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Relationship with host government
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod1_host_gov",
    label = "Relationship With Host Government",
    choices = c(
      "Friendly relationship with government", 
      "Criticized by government",  
      "Under government crackdown"
    ),
    # selected = "Friendly relationship with government",
    selected = ifelse(
      sum(prod_data[12:13,2]) == 0, "Friendly relationship with government",
      as.character(prod_data[12:13,][which(prod_data[12:13,2] == 1), 1])
    ),
    width = "450px"
  )
})
```

### Product 2

```{r prod2-inputs}
# Naming
textInput(
  "org2_name",
  label = "Product Name:",
  value = "Product 2",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Product
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_prod",
    label = "Product:",
    choice = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,3] == 1), 1]),
    width = "450px"
  )
})

# Issue area
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_issue", 
    label = "Issue Area:",
    choices = c("Emergency response", "Environment", "Human rights", "Refugee relief"),
    # selected = "Environment",
    selected = ifelse(
      sum(prod_data[5:7,3]) == 0, "Emergency response",
      as.character(prod_data[5:7,][which(prod_data[5:7,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial transparency
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_fin_trans",
    label = "Financial Transparency:",
    choices = c(
      "Doesn’t engage in financial transparency", 
      "Engages in financial transparency"
    ),
    # selected = "Engages in financial transparency",
    selected = ifelse(
      sum(prod_data[8,3]) == 0, "Doesn’t engage in financial transparency",
      as.character(prod_data[8,][which(prod_data[8,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial accountability
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_fin_account",
    label = "Financial Accountability:",
    choices = c(
      "Doesn’t engage in financial accountability", 
      "Engages in financial accountability"
    ),
    # selected = "Engages in financial accountability",
    selected = ifelse(
      sum(prod_data[9,3]) == 0, "Doesn’t engage in financial accountability",
      as.character(prod_data[9,][which(prod_data[9,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Funding sources
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_funding",
    label = "Funding Source:",
    choices = c(
      "Many small private donations", 
      "Handful of wealthy private donors", 
      "Government grants"
    ),
    # selected = "Many small private donations",
    selected = ifelse(
      sum(prod_data[10:11,3]) == 0, "Many small private donations",
      as.character(prod_data[10:11,][which(prod_data[10:11,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Relationship with host government
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod2_host_gov",
    label = "Relationship With Host Government",
    choices = c(
      "Friendly relationship with government", 
      "Criticized by government",  
      "Under government crackdown"
    ),
    # selected = "Friendly relationship with government",
    selected = ifelse(
      sum(prod_data[12:13,3]) == 0, "Friendly relationship with government",
      as.character(prod_data[12:13,][which(prod_data[12:13,3] == 1), 1])
    ),
    width = "450px"
  )
})
```

### Product 3

```{r org3-inputs}
# Naming
textInput(
  "prod3_name",
  label = "Product Name:",
  value = "Product 3",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Product
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_prod",
    label = "Product:",
    choice = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,4] == 1), 1]),
    width = "450px"
  )
})

# Issue area
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_issue", 
    label = "Issue Area:",
    choices = c("Emergency response", "Environment", "Human rights", "Refugee relief"),
    # selected = "Human rights",
    selected = ifelse(
      sum(prod_data[5:7,4]) == 0, "Emergency response",
      as.character(prod_data[5:7,][which(prod_data[5:7,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial transparency
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_fin_trans",
    label = "Financial Transparency:",
    choices = c(
      "Doesn’t engage in financial transparency", 
      "Engages in financial transparency"
    ),
    # selected = "Engages in financial transparency",
    selected = ifelse(
      sum(prod_data[8,4]) == 0, "Doesn’t engage in financial transparency",
      as.character(prod_data[8,][which(prod_data[8,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial accountability
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_fin_account",
    label = "Financial Accountability:",
    choices = c(
      "Doesn’t engage in financial accountability", 
      "Engages in financial accountability"
    ),
    # selected = "Engages in financial accountability",
    selected = ifelse(
      sum(prod_data[9,4]) == 0, "Doesn’t engage in financial accountability",
      as.character(prod_data[9,][which(prod_data[9,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Funding sources
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_funding",
    label = "Funding Source:",
    choices = c(
      "Many small private donations", 
      "Handful of wealthy private donors", 
      "Government grants"
    ),
    # selected = "Many small private donations",
    selected = ifelse(
      sum(prod_data[10:11,4]) == 0, "Many small private donations",
      as.character(prod_data[10:11,][which(prod_data[10:11,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Relationship with host government
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod3_host_gov",
    label = "Relationship With Host Government",
    choices = c(
      "Friendly relationship with government", 
      "Criticized by government",  
      "Under government crackdown"
    ),
    # selected = "Friendly relationship with government",
    selected = ifelse(
      sum(prod_data[12:13,4]) == 0, "Friendly relationship with government",
      as.character(prod_data[12:13,][which(prod_data[12:13,4] == 1), 1])
    ),
    width = "450px"
  )
})
```

### Product 4

```{r org4-inputs}
# Naming
textInput(
  "prod4_name",
  label = "Product Name:",
  value = "Product 4",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Product
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_prod",
    label = "Product:",
    choice = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,5] == 1), 1]),
    width = "450px"
  )
})

# Issue area
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_issue", 
    label = "Issue Area:",
    choices = c("Emergency response", "Environment", "Human rights", "Refugee relief"),
    # selected = "Refugee relief",
    selected = ifelse(
      sum(prod_data[5:7,5]) == 0, "Emergency response",
      as.character(prod_data[5:7,][which(prod_data[5:7,5] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial transparency
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_fin_trans",
    label = "Financial Transparency:",
    choices = c(
      "Doesn’t engage in financial transparency", 
      "Engages in financial transparency"
    ),
    # selected = "Engages in financial transparency",
    selected = ifelse(
      sum(prod_data[8,5]) == 0, "Doesn’t engage in financial transparency",
      as.character(prod_data[8,][which(prod_data[8,5] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial accountability
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_fin_account",
    label = "Financial Accountability:",
    choices = c(
      "Doesn’t engage in financial accountability", 
      "Engages in financial accountability"
    ),
    # selected = "Engages in financial accountability",
    selected = ifelse(
      sum(prod_data[9,5]) == 0, "Doesn’t engage in financial accountability",
      as.character(prod_data[9,][which(prod_data[9,5] == 1), 1])
    ),
    width = "450px"
  )
})

# Funding sources
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_funding",
    label = "Funding Source:",
    choices = c(
      "Many small private donations", 
      "Handful of wealthy private donors", 
      "Government grants"
    ),
    # selected = "Many small private donations",
    selected = ifelse(
      sum(prod_data[10:11,5]) == 0, "Many small private donations",
      as.character(prod_data[10:11,][which(prod_data[10:11,5] == 1), 1])
    ),
    width = "450px"
  )
})

# Relationship with host government
renderUI({
  prod_data = organization_data()
  selectInput(
    "prod4_host_gov",
    label = "Relationship With Host Government",
    choices = c(
      "Friendly relationship with government", 
      "Criticized by government",  
      "Under government crackdown"
    ),
    # selected = "Friendly relationship with government",
    selected = ifelse(
      sum(prod_data[12:13,5]) == 0, "Friendly relationship with government",
      as.character(prod_data[12:13,][which(prod_data[12:13,5] == 1), 1])
    ),
    width = "450px"
  )
})
```

### Segment 1??

```{r per1-inputs}
# Naming
textInput(
  "per1_name",
  label = "Persona Name:",
  value = "Persona 1",
  placeholder = "Enter Persona Name",
  width = "450px"
)
 
# Follow national news
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_national_news",
    label = "Follow national news:",
    choices = c("Rarely", "Once a week", "At least once a day"),
    # selected = "At least once a day",
    selected = ifelse(
      sum(per_data[2:3,2]) == 0, "Rarely",
      as.character(per_data[2:3,][which(per_data[2:3,2] == 1), 1])
    ),
    width = "450px"
  )
1078
 
})
1079
 
1080
 
# Follow international news
1081
 
renderUI({
1082
 
  per_data = persona_data()
1083
 
  selectInput(
1084
 
    "per1_international_news",
1085
 
    label = "Follow international news:",
1086
 
    choices = c("Never", "Sometimes", "Always"),
1087
 
    # selected = "Always",
1088
 
    selected = ifelse(
1089
 
      sum(per_data[4:5,2]) == 0, "Never",
1090
 
      as.character(per_data[4:5,][which(per_data[4:5,2] == 1), 1])
1091
 
    ),
1092
 
    width = "450px"
1093
 
  )
1094
 
})
1095
 
1096
 
# Mediums to follow news
1097
 
renderUI({
1098
 
  per_data = persona_data()
1099
 
  selectInput(
1100
 
    "per1_news_medium",
1101
 
    label = "Medium to follow news:",
1102
 
    choices = c(
1103
 
      "TV",
1104
 
      "Print",
1105
 
      "Online (not social media)",
1106
 
      "Social media",
1107
 
      "Radio",
1108
 
      "Email newsletter",
1109
 
      "News app"
1110
 
    ),
1111
 
    multiple = TRUE,
1112
 
    # selected = c("TV", "Print", "Social media"),
1113
 
    selected = deframe(per_data[6:12,][which(per_data[6:12,2] == 1), 1]),
1114
 
    width = "450px"
1115
 
  )
1116
 
})
1117
 
1118
 
# Follow government and public affairs
1119
 
renderUI({
1120
 
  per_data = persona_data()
1121
 
  selectInput(
1122
 
    "per1_follow_gov",
1123
 
    label = "Follow government & public affairs:",
1124
 
    choices = c("Not Often", "Often"),
1125
 
    # selected = "Often",
1126
 
    selected = ifelse(
1127
 
      sum(per_data[13,2]) == 0, "Not Often",
1128
 
      as.character(per_data[13,][which(per_data[13,2] == 1), 1])
1129
 
    ),
1130
 
    width = "450px"
1131
 
  )
1132
 
})
1133
 
1134
 
# Traveled to a developing country
1135
 
renderUI({
1136
 
  per_data = persona_data()
1137
 
  selectInput(
1138
 
    "per1_travel_developing",
1139
 
    label = "Travel to developing country:",
1140
 
    choices = c("Hasn't traveled to a developing country", "Traveled to a developing country"),
1141
 
    # selected = "Traveled to a developing country",
1142
 
    selected = ifelse(
1143
 
      sum(per_data[14,2]) == 0, "Hasn't traveled to a developing country",
1144
 
      as.character(per_data[14,][which(per_data[14,2] == 1), 1])
1145
 
    ),
1146
 
    width = "450px"
1147
 
  )
1148
 
})
1149
 
1150
 
# Liberal to Conservative
1151
 
renderUI({
1152
 
  per_data = persona_data()
1153
 
  selectInput(
1154
 
    "per1_political_pref",
1155
 
    label = "Political views from liberal to conservative:",
1156
 
    choices = c(
1157
 
      "Extremely liberal",
1158
 
      "Somewhat liberal",
1159
 
      "Slightly liberal",
1160
 
      "Moderate",
1161
 
      "Slightly conservative",
1162
 
      "Somewhat conservative",
1163
 
      "Extremely conservative"
1164
 
    ),
1165
 
    # selected = "Somewhat liberal",
1166
 
    selected = ifelse(
1167
 
      sum(per_data[15:20,2]) == 0, "Extremely liberal",
1168
 
      as.character(per_data[15:20,][which(per_data[15:20,2] == 1), 1])
1169
 
    ),
1170
 
    width = "450px"
1171
 
  )
1172
 
})

# Trust in political institutions
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_institution_trust",
    label = "Political institution trust from none to complete:",
    choices = c(
      "No trust at all in political institutions",
      "Very little trust in political institutions",
      "Little trust in political institutions",
      "Neutral trust in political institutions",
      "Some trust in political institutions",
      "A lot of trust in political institutions",
      "Complete trust in political institutions"
    ),
    # selected = "Complete trust in political institutions",
    selected = ifelse(
      sum(per_data[21:26,2]) == 0, "No trust at all in political institutions",
      as.character(per_data[21:26,][which(per_data[21:26,2] == 1), 1])
    ),
    width = "450px"
  )
})

# People should be more charitable
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_others_charitable",
    label = "People should be more charitable:",
    choices = c(
      "Strongly disagree",
      "Disagree",
      "Somewhat disagree",
      "Neutral",
      "Somewhat agree",
      "Agree",
      "Strongly agree"
    ),
    # selected = "Strongly agree",
    selected = ifelse(
      sum(per_data[27:32,2]) == 0, "Strongly disagree",
      as.character(per_data[27:32,][which(per_data[27:32,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Religious attendance
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_worship_attendance",
    label = "Worship service attendance:",
    choices = c(
      "Not sure",
      "Rarely attend",
      "Attend at least once a month"
    ),
    # selected = "Attend at least once a month",
    selected = ifelse(
      sum(per_data[33:34,2]) == 0, "Not sure",
      as.character(per_data[33:34,][which(per_data[33:34,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Importance of religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_religion_importance",
    label = "Importance of religion:",
    choices = c("Not important", "Important"),
    # selected = "Important",
    selected = ifelse(
      sum(per_data[35,2]) == 0, "Not important",
      as.character(per_data[35,][which(per_data[35,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_religion",
    label = "Religion:",
    choices = c(
      "Catholic",
      'Protestant',
      'Christian Orthodox',
      'Jewish',
      'Muslim',
      'Sikh',
      'Hindu',
      'Buddhist',
      'Atheist',
      'Other religion'
    ),
    # selected = 'Protestant',
     selected = ifelse(
      sum(per_data[36:44,2]) == 0, "Catholic",
      as.character(per_data[36:44,][which(per_data[36:44,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Importance of trusting charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_charity_importance",
    label = "Charity Importance:",
    choices = c(
      "Not at all important",
      "Very unimportant",
      "Somewhat unimportant",
      "Neutral importance",
      "Somewhat important",
      "Very important",
      "Essential"
    ),
    # selected = "Somewhat unimportant",
    selected = ifelse(
      sum(per_data[45:50,2]) == 0, "Not at all important",
      as.character(per_data[45:50,][which(per_data[45:50,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Trust in charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_trust_in_charity",
    label = "Charity Trust:",
    choices = c(
      "No trust at all in charities",
      "Very little trust in charities",
      "Little trust in charities",
      "Neutral trust in charities",
      "Some trust in charities",
      "A lot of trust in charities",
      "Complete trust in charities"
    ),
    # selected = "Complete trust in charities",
     selected = ifelse(
      sum(per_data[51:56,2]) == 0, "No trust at all in charities",
      as.character(per_data[51:56,][which(per_data[51:56,2] == 1), 1])
    ),
    width = "450px"
  )

})

# Donation frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_donation_frequency",
    label = "Donation Frequency:",
    choices = c('Donate more than once a month, less than once a year', 'Donate at least once a month'),
    # selected = "Donate at least once a month",
    selected = ifelse(
      sum(per_data[57,2]) == 0, "Donate more than once a month, less than once a year",
      as.character(per_data[57,][which(per_data[57,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Donated last year
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_donation_amount",
    label = "Donation Amount Last Year:",
    choices = c(
      '$1-$49',
      '$50-$99',
      '$100-$499',
      '$500-$999',
      '$1,000-$4,999',
      '$5,000-$9,999',
      '$10,000+'
    ),
    # selected = "$100-$499",
    selected = ifelse(
      sum(per_data[58:63,2]) == 0, "$1-$49",
      as.character(per_data[58:63,][which(per_data[58:63,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteered in past 12 months
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_volunteer_12",
    label = "Volunteered in last 12 Months:",
    choices = c("Haven't volunteered in past 12 months", "Volunteered in past 12 months"),
    # selected = "Volunteered in past 12 months",
    selected = ifelse(
      sum(per_data[64,2]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[64,][which(per_data[64,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteer frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_volunteer_frequency",
    label = "Volunteer Frequency:",
    choices = c(
      "Haven't volunteered in past 12 months",
      "Rarely volunteer",
      "Volunteer more than once a month, less than once a year",
      "Volunteer at least once a month"
    ),
    # selected = "Volunteer at least once a month",
    selected = ifelse(
      sum(per_data[65:67,2]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[65:67,][which(per_data[65:67,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# History of activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_personal_activism",
    label = "Personal Activism:",
    choices = c('Not personally involved', 'Personally involved'),
    # selected = "Personally involved",
    selected = ifelse(
      sum(per_data[68,2]) == 0, "Not personally involved",
      as.character(per_data[68,][which(per_data[68,2] == 1), 1])
    ),
    width = "450px"
  )
})

# History of family activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_family_activism",
    label = "Family Activism:",
    choices = c('Family not involved', 'Family involved'),
    # selected = "Family involved",
    selected = ifelse(
      sum(per_data[69,2]) == 0, "Family not involved",
      as.character(per_data[69,][which(per_data[69,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Church or religious organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_religious_member",
    label = "Church Membership:",
    choices = c("Don't belong to church",'Inactive church member', 'Active church member'),
    # selected = "Don't belong to church",
    selected = ifelse(
      sum(per_data[70:71,2]) == 0, "Don't belong to church",
      as.character(per_data[70:71,][which(per_data[70:71,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Sport or recreational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_sport_member",
    label = "Sport or Recreational Membership:",
    choices = c(
      "Don't belong to sports or rec organization", 
      'Inactive sports or rec organization member',
      'Active sports or rec organization member'
    ),
    # selected = "Don't belong to sports or rec organization",
    selected = ifelse(
      sum(per_data[72:73,2]) == 0, "Don't belong to sports or rec organization",
      as.character(per_data[72:73,][which(per_data[72:73,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Art, music, or educational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_art_member",
    label = "Art, Music, or Educational Membership:",
    choices = c(
      "Don't belong to educational organization",
      'Inactive art, music, or educational organization member',
      'Active art, music, or educational organization member'
    ),
    # selected = "Don't belong to educational organization",
    selected = ifelse(
      sum(per_data[74:75,2]) == 0, "Don't belong to educational organization",
      as.character(per_data[74:75,][which(per_data[74:75,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Labor union
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_labor_member",
    label = "Labor Union Membership:",
    choices = c(
      "Don't belong to union",
      'Inactive union member', 
      'Active union member'
    ),
    # selected = "Don't belong to union",
    selected = ifelse(
      sum(per_data[76:77,2]) == 0, "Don't belong to union",
      as.character(per_data[76:77,][which(per_data[76:77,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Political party
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_political_member",
    label = "Political Party Membership:",
    choices = c(
      "Don't belong to political party",
      'Inactive political party member',
      'Active political party member'
    ),
    # selected = "Active political party member",
    selected = ifelse(
      sum(per_data[78:79,2]) == 0, "Don't belong to political party",
      as.character(per_data[78:79,][which(per_data[78:79,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Environmental organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_environmental_member",
    label = "Environmental Organization Membership:",
    choices = c(
      "Don't belong to environmental organization",
      'Inactive environmental organization member',
      'Active environmental organization member'
    ),
    # selected = "Don't belong to environmental organization",
    selected = ifelse(
      sum(per_data[80:81,2]) == 0, "Don't belong to environmental organization",
      as.character(per_data[80:81,][which(per_data[80:81,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Professional association
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_professional_member",
    label = "Professional Association Membership:",
    choices = c(
      "Don't belong to professional association",
      'Inactive professional association member',
      'Active professional association member'
    ),
    # selected = "Don't belong to professional association",
    selected = ifelse(
      sum(per_data[82:83,2]) == 0, "Don't belong to professional association",
      as.character(per_data[82:83,][which(per_data[82:83,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Humanitarian or charitable organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_humanitarian_member",
    label = "Humanitarian or Charitable Organization Membership:",
    choices = c(
      "Don't belong to humanitarian or charitable organization",
      'Inactive humanitarian or charitable organization member',
      'Active humanitarian or charitable organization member'
    ),
    # selected = "Active humanitarian or charitable organization member",
    selected = ifelse(
      sum(per_data[84:85,2]) == 0, "Don't belong to humanitarian or charitable organization",
      as.character(per_data[84:85,][which(per_data[84:85,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Consumer organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_consumer_member",
    label = "Consumer Organization Membership:",
    choices = c(
      "Don't belong to consumer organization",
      'Inactive consumer organization member',
      'Active consumer organization member'
    ),
    # selected = "Don't belong to consumer organization",
    selected = ifelse(
      sum(per_data[86:87,2]) == 0, "Don't belong to consumer organization",
      as.character(per_data[86:87,][which(per_data[86:87,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Other organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_other_member",
    label = "Other Organization Membership:",
    choices = c(
      "Don't belong to another organization",
      'Inactive member in another organization',
      'Active member in another organization'
    ),
    # selected = "Don't belong to another organization",
    selected = ifelse(
      sum(per_data[88:89,2]) == 0, "Don't belong to another organization",
      as.character(per_data[88:89,][which(per_data[88:89,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Gender
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_gender",
    label = "Gender:",
    choices = c(
      "Male",
      "Female",
      "Transgender",
      "Prefer not to say",
      "Other gender"
    ),
    # selected = "Male",
    selected = ifelse(
      sum(per_data[90:93,2]) == 0, "Male",
      as.character(per_data[90:93,][which(per_data[90:93,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Marital status
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_marital_status",
    label = "Marital Status:",
    choices = c(
      "Married",
      "Widowed",
      "Divorced",
      "Separated",
      "Never married"
    ),
    # selected = "Married",
    selected = ifelse(
      sum(per_data[94:97,2]) == 0, "Married",
      as.character(per_data[94:97,][which(per_data[94:97,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Education
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_education",
    label = "Education:",
    choices = c(
      "Less than high school",
      "High school graduate",
      "Some college",
      "2 year degree",
      "4 year degree",
      "Graduate or professional degree",
      "Doctorate"
    ),
    # selected = "2 year degree",
    selected = ifelse(
      sum(per_data[98:103,2]) == 0, "Less than high school",
      as.character(per_data[98:103,][which(per_data[98:103,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Income
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_income",
    label = "Income:",
    choices = c('Less than median of $61,372', 'More than median of $61,372'),
    # selected = "More than median of $61,372",
    selected = ifelse(
      sum(per_data[104,2]) == 0, "Less than median of $61,372",
      as.character(per_data[104,][which(per_data[104,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
# Race
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_race",
    label = "Race:",
    choices = c(
      'White',
      'Black or African American',
      'American Indian or Alaskan Native',
      'Asian',
      'Native Hawaiian or Pacific Islander',
      'Other race'
    ),
    multiple = TRUE,
    # selected = "White",
    selected = deframe(per_data[105:110,][which(per_data[105:110,2] == 1), 1]),
    width = "450px"
  )
})
 
# Age
renderUI({
  per_data = persona_data()
  selectInput(
    "per1_age",
    label = "Age:",
    choices = c('Less than median age of 36', "More than median age of 36"),
    # selected = "Less than median age of 36",
    selected = ifelse(
      sum(per_data[111,2]) == 0, "Less than median age of 36",
      as.character(per_data[111,][which(per_data[111,2] == 1), 1])
    ),
    width = "450px"
  )
})
 
```

### Segment 2

```{r per2-inputs}
# Naming
textInput(
  "per2_name",
  label = "Persona Name:",
  value = "Persona 2",
  placeholder = "Enter Persona Name",
  width = "450px"
)

# Follow national news
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_national_news",
    label = "Follow national news:",
    choices = c("Rarely", "Once a week", "At least once a day"),
    # selected = "At least once a day",
    selected = ifelse(
      sum(per_data[2:3,3]) == 0, "Rarely",
      as.character(per_data[2:3,][which(per_data[2:3,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Follow international news
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_international_news",
    label = "Follow international news:",
    choices = c("Never", "Sometimes", "Always"),
    # selected = "Always",
    selected = ifelse(
      sum(per_data[4:5,3]) == 0, "Never",
      as.character(per_data[4:5,][which(per_data[4:5,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Mediums to follow news
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_news_medium",
    label = "Medium to follow news:",
    choices = c(
      "TV",
      "Print",
      "Online (not social media)",
      "Social media",
      "Radio",
      "Email newsletter",
      "News app"
    ),
    multiple = TRUE,
    # selected = c("TV", "Print", "Social media"),
    selected = deframe(per_data[6:12,][which(per_data[6:12,3] == 1), 1]),
    width = "450px"
  )
})

# Follow government and public affairs
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_follow_gov",
    label = "Follow government & public affairs:",
    choices = c("Not Often", "Often"),
    # selected = "Often",
    selected = ifelse(
      sum(per_data[13,3]) == 0, "Not Often",
      as.character(per_data[13,][which(per_data[13,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Traveled to a developing country
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_travel_developing",
    label = "Travel to developing country:",
    choices = c("Hasn't traveled to a developing country", "Traveled to a developing country"),
    # selected = "Traveled to a developing country",
    selected = ifelse(
      sum(per_data[14,3]) == 0, "Hasn't traveled to a developing country",
      as.character(per_data[14,][which(per_data[14,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Liberal to Conservative
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_political_pref",
    label = "Political views from liberal to conservative:",
    choices = c(
      "Extremely liberal",
      "Somewhat liberal",
      "Slightly liberal",
      "Moderate",
      "Slightly conservative",
      "Somewhat conservative",
      "Extremely conservative"
    ),
    # selected = "Somewhat liberal",
    selected = ifelse(
      sum(per_data[15:20,3]) == 0, "Extremely liberal",
      as.character(per_data[15:20,][which(per_data[15:20,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Trust in political institutions
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_institution_trust",
    label = "Political institution trust from none to complete:",
    choices = c(
      "No trust at all in political institutions",
      "Very little trust in political institutions",
      "Little trust in political institutions",
      "Neutral trust in political institutions",
      "Some trust in political institutions",
      "A lot of trust in political institutions",
      "Complete trust in political institutions"
    ),
    # selected = "Complete trust in political institutions",
    selected = ifelse(
      sum(per_data[21:26,3]) == 0, "No trust at all in political institutions",
      as.character(per_data[21:26,][which(per_data[21:26,3] == 1), 1])
    ),
    width = "450px"
  )
})

# People should be more charitable
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_others_charitable",
    label = "People should be more charitable:",
    choices = c(
      "Strongly disagree",
      "Disagree",
      "Somewhat disagree",
      "Neutral",
      "Somewhat agree",
      "Agree",
      "Strongly agree"
    ),
    # selected = "Strongly agree",
    selected = ifelse(
      sum(per_data[27:32,3]) == 0, "Strongly disagree",
      as.character(per_data[27:32,][which(per_data[27:32,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Religious attendance
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_worship_attendance",
    label = "Worship service attendance:",
    choices = c(
      "Not sure",
      "Rarely attend",
      "Attend at least once a month"
    ),
    # selected = "Attend at least once a month",
    selected = ifelse(
      sum(per_data[33:34,3]) == 0, "Not sure",
      as.character(per_data[33:34,][which(per_data[33:34,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Importance of religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_religion_importance",
    label = "Importance of religion:",
    choices = c("Not important", "Important"),
    # selected = "Important",
    selected = ifelse(
      sum(per_data[35,3]) == 0, "Not important",
      as.character(per_data[35,][which(per_data[35,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_religion",
    label = "Religion:",
    choices = c(
      'Catholic',
      'Protestant',
      'Christian Orthodox',
      'Jewish',
      'Muslim',
      'Sikh',
      'Hindu',
      'Buddhist',
      'Atheist',
      'Other religion'
    ),
    # selected = 'Protestant',
    selected = ifelse(
      sum(per_data[36:44,3]) == 0, "Catholic",
      as.character(per_data[36:44,][which(per_data[36:44,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Importance of trusting charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_charity_importance",
    label = "Charity Importance:",
    choices = c(
      "Not at all important",
      "Very unimportant",
      "Somewhat unimportant",
      "Neutral importance",
      "Somewhat important",
      "Very important",
      "Essential"
    ),
    # selected = "Somewhat unimportant",
    selected = ifelse(
      sum(per_data[45:50,3]) == 0, "Not at all important",
      as.character(per_data[45:50,][which(per_data[45:50,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Trust in charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_trust_in_charity",
    label = "Charity Trust:",
    choices = c(
      "No trust at all in charities",
      "Very little trust in charities",
      "Little trust in charities",
      "Neutral trust in charities",
      "Some trust in charities",
      "A lot of trust in charities",
      "Complete trust in charities"
    ),
    # selected = "Complete trust in charities",
    selected = ifelse(
      sum(per_data[51:56,3]) == 0, "No trust at all in charities",
      as.character(per_data[51:56,][which(per_data[51:56,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Donation frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_donation_frequency",
    label = "Donation Frequency:",
    choices = c('Donate more than once a month, less than once a year', 'Donate at least once a month'),
    # selected = "Donate at least once a month",
    selected = ifelse(
      sum(per_data[57,3]) == 0, "Donate more than once a month, less than once a year",
      as.character(per_data[57,][which(per_data[57,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Donated last year
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_donation_amount",
    label = "Donation Amount Last Year:",
    choices = c(
      '$1-$49',
      '$50-$99',
      '$100-$499',
      '$500-$999',
      '$1,000-$4,999',
      '$5,000-$9,999',
      '$10,000+'
    ),
    # selected = "$100-$499",
    selected = ifelse(
      sum(per_data[58:63,3]) == 0, "$1-$49",
      as.character(per_data[58:63,][which(per_data[58:63,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteered in past 12 months
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_volunteer_12",
    label = "Volunteered in last 12 Months:",
    choices = c("Haven't volunteered in past 12 months", "Volunteered in past 12 months"),
    # selected = "Volunteered in past 12 months",
    selected = ifelse(
      sum(per_data[64,3]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[64,][which(per_data[64,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteer frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_volunteer_frequency",
    label = "Volunteer Frequency:",
    choices = c(
      "Haven't volunteered in past 12 months",
      "Rarely volunteer",
      "Volunteer more than once a month, less than once a year",
      "Volunteer at least once a month"
    ),
    # selected = "Volunteer at least once a month",
    selected = ifelse(
      sum(per_data[65:67,3]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[65:67,][which(per_data[65:67,3] == 1), 1])
    ),
    width = "450px"
  )
})

# History of activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_personal_activism",
    label = "Personal Activism:",
    choices = c('Not personally involved', 'Personally involved'),
    # selected = "Personally involved",
    selected = ifelse(
      sum(per_data[68,3]) == 0, "Not personally involved",
      as.character(per_data[68,][which(per_data[68,3] == 1), 1])
    ),
    width = "450px"
  )
})

# History of family activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_family_activism",
    label = "Family Activism:",
    choices = c('Family not involved', 'Family involved'),
    # selected = "Family involved",
    selected = ifelse(
      sum(per_data[69,3]) == 0, "Family not involved",
      as.character(per_data[69,][which(per_data[69,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Church or religious organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_religious_member",
    label = "Church Membership:",
    choices = c("Don't belong to church",'Inactive church member', 'Active church member'),
    # selected = "Don't belong to church",
    selected = ifelse(
      sum(per_data[70:71,3]) == 0, "Don't belong to church",
      as.character(per_data[70:71,][which(per_data[70:71,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Sport or recreational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_sport_member",
    label = "Sport or Recreational Membership:",
    choices = c(
      "Don't belong to sports or rec organization", 
      'Inactive sports or rec organization member',
      'Active sports or rec organization member'
    ),
    # selected = "Don't belong to sports or rec organization",
    selected = ifelse(
      sum(per_data[72:73,3]) == 0, "Don't belong to sports or rec organization",
      as.character(per_data[72:73,][which(per_data[72:73,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Art, music, or educational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_art_member",
    label = "Art, Music, or Educational Membership:",
    choices = c(
      "Don't belong to educational organization",
      'Inactive art, music, or educational organization member',
      'Active art, music, or educational organization member'
    ),
    # selected = "Don't belong to educational organization",
    selected = ifelse(
      sum(per_data[74:75,3]) == 0, "Don't belong to educational organization",
      as.character(per_data[74:75,][which(per_data[74:75,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Labor union
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_labor_member",
    label = "Labor Union Membership:",
    choices = c("Don't belong to union", 'Inactive union member', 'Active union member'),
    # selected = "Don't belong to union",
    selected = ifelse(
      sum(per_data[76:77,3]) == 0, "Don't belong to union",
      as.character(per_data[76:77,][which(per_data[76:77,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Political party
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_political_member",
    label = "Political Party Membership:",
    choices = c(
      "Don't belong to political party",
      'Inactive political party member',
      'Active political party member'
    ),
    # selected = "Active political party member",
    selected = ifelse(
      sum(per_data[78:79,3]) == 0, "Don't belong to political party",
      as.character(per_data[78:79,][which(per_data[78:79,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Environmental organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_environmental_member",
    label = "Environmental Organization Membership:",
    choices = c(
      "Don't belong to environmental organization",
      'Inactive environmental organization member',
      'Active environmental organization member'
    ),
    # selected = "Don't belong to environmental organization",
    selected = ifelse(
      sum(per_data[80:81,3]) == 0, "Don't belong to environmental organization",
      as.character(per_data[80:81,][which(per_data[80:81,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Professional association
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_professional_member",
    label = "Professional Association Membership:",
    choices = c(
      "Don't belong to professional association",
      'Inactive professional association member',
      'Active professional association member'
    ),
    # selected = "Don't belong to professional association",
    selected = ifelse(
      sum(per_data[82:83,3]) == 0, "Don't belong to professional association",
      as.character(per_data[82:83,][which(per_data[82:83,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Humanitarian or charitable organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_humanitarian_member",
    label = "Humanitarian or Charitable Organization Membership:",
    choices = c(
      "Don't belong to humanitarian or charitable organization",
      'Inactive humanitarian or charitable organization member',
      'Active humanitarian or charitable organization member'
    ),
    # selected = "Active humanitarian or charitable organization member",
    selected = ifelse(
      sum(per_data[84:85,3]) == 0, "Don't belong to humanitarian or charitable organization",
      as.character(per_data[84:85,][which(per_data[84:85,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Consumer organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_consumer_member",
    label = "Consumer Organization Membership:",
    choices = c(
      "Don't belong to consumer organization",
      'Inactive consumer organization member',
      'Active consumer organization member'
    ),
    # selected = "Don't belong to consumer organization",
    selected = ifelse(
      sum(per_data[86:87,3]) == 0, "Don't belong to consumer organization",
      as.character(per_data[86:87,][which(per_data[86:87,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Other organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_other_member",
    label = "Other Organization Membership:",
    choices = c(
      "Don't belong to another organization",
      'Inactive member in another organization',
      'Active member in another organization'
    ),
    # selected = "Don't belong to another organization",
    selected = ifelse(
      sum(per_data[88:89,3]) == 0, "Don't belong to another organization",
      as.character(per_data[88:89,][which(per_data[88:89,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Gender
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_gender",
    label = "Gender:",
    choices = c(
      "Male",
      "Female",
      "Transgender",
      "Prefer not to say",
      "Other gender"
    ),
    # selected = "Male",
    selected = ifelse(
      sum(per_data[90:93,3]) == 0, "Male",
      as.character(per_data[90:93,][which(per_data[90:93,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Marital status
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_marital_status",
    label = "Marital Status:",
    choices = c(
      "Married",
      "Widowed",
      "Divorced",
      "Separated",
      "Never married"
    ),
    # selected = "Married",
    selected = ifelse(
      sum(per_data[94:97,3]) == 0, "Married",
      as.character(per_data[94:97,][which(per_data[94:97,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Education
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_education",
    label = "Education:",
    choices = c(
      "Less than high school",
      "High school graduate",
      "Some college",
      "2 year degree",
      "4 year degree",
      "Graduate or professional degree",
      "Doctorate"
    ),
    # selected = "Some college",
    selected = ifelse(
      sum(per_data[98:103,3]) == 0, "Less than high school",
      as.character(per_data[98:103,][which(per_data[98:103,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Income
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_income",
    label = "Income:",
    choices = c('Less than median of $61,372', 'More than median of $61,372'),
    # selected = "More than median of $61,372",
    selected = ifelse(
      sum(per_data[104,3]) == 0, "Less than median of $61,372",
      as.character(per_data[104,][which(per_data[104,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Race
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_race",
    label = "Race:",
    choices = c(
      'White',
      'Black or African American',
      'American Indian or Alaskan Native',
      'Asian',
      'Native Hawaiian or Pacific Islander',
      'Other race'
    ),
    multiple = TRUE,
    # selected = "American Indian or Alaskan Native",
    selected = deframe(per_data[105:110,][which(per_data[105:110,3] == 1), 1]),
    width = "450px"
  )
})

# Age
renderUI({
  per_data = persona_data()
  selectInput(
    "per2_age",
    label = "Age:",
    choices = c('Less than median age of 36', "More than median age of 36"),
    # selected = "Less than median age of 36",
    selected = ifelse(
      sum(per_data[111,3]) == 0, "Less than median age of 36",
      as.character(per_data[111,][which(per_data[111,3] == 1), 1])
    ),
    width = "450px"
  )
})
```

### Segment 3

```{r per3-inputs}
# Naming
textInput(
  "per3_name",
  label = "Persona Name:",
  value = "Persona 3",
  placeholder = "Enter Persona Name",
  width = "450px"
)

# Follow national news
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_national_news",
    label = "Follow national news:",
    choices = c("Rarely", "Once a week", "At least once a day"),
    # selected = "At least once a day",
    selected = ifelse(
      sum(per_data[2:3,4]) == 0, "Rarely",
      as.character(per_data[2:3,][which(per_data[2:3,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Follow international news
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_international_news",
    label = "Follow international news:",
    choices = c("Never", "Sometimes", "Always"),
    # selected = "Always",
    selected = ifelse(
      sum(per_data[4:5,4]) == 0, "Never",
      as.character(per_data[4:5,][which(per_data[4:5,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Mediums to follow news
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_news_medium",
    label = "Medium to follow news:",
    choices = c(
      "TV",
      "Print",
      "Online (not social media)",
      "Social media",
      "Radio",
      "Email newsletter",
      "News app"
    ),
    multiple = TRUE,
    # selected = c("TV", "Print", "Social media"),
    selected = deframe(per_data[6:12,][which(per_data[6:12,4] == 1), 1]),
    width = "450px"
  )
})

# Follow government and public affairs
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_follow_gov",
    label = "Follow government & public affairs:",
    choices = c("Not Often", "Often"),
    # selected = "Often",
    selected = ifelse(
      sum(per_data[13,4]) == 0, "Not Often",
      as.character(per_data[13,][which(per_data[13,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Traveled to a developing country
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_travel_developing",
    label = "Travel to developing country:",
    choices = c("Hasn't traveled to a developing country", "Traveled to a developing country"),
    # selected = "Traveled to a developing country",
    selected = ifelse(
      sum(per_data[14,4]) == 0, "Hasn't traveled to a developing country",
      as.character(per_data[14,][which(per_data[14,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Liberal to Conservative
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_political_pref",
    label = "Political views from liberal to conservative:",
    choices = c(
      "Extremely liberal",
      "Somewhat liberal",
      "Slightly liberal",
      "Moderate",
      "Slightly conservative",
      "Somewhat conservative",
      "Extremely conservative"
    ),
    # selected = "Somewhat liberal",
    selected = ifelse(
      sum(per_data[15:20,4]) == 0, "Extremely liberal",
      as.character(per_data[15:20,][which(per_data[15:20,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Trust in political institutions
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_institution_trust",
    label = "Political institution trust from none to complete:",
    choices = c(
      "No trust at all in political institutions",
      "Very little trust in political institutions",
      "Little trust in political institutions",
      "Neutral trust in political institutions",
      "Some trust in political institutions",
      "A lot of trust in political institutions",
      "Complete trust in political institutions"
    ),
    # selected = "Complete trust in political institutions",
    selected = ifelse(
      sum(per_data[21:26,4]) == 0, "No trust at all in political institutions",
      as.character(per_data[21:26,][which(per_data[21:26,4] == 1), 1])
    ),
    width = "450px"
  )
})

# People should be more charitable
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_others_charitable",
    label = "People should be more charitable:",
    choices = c(
      "Strongly disagree",
      "Disagree",
      "Somewhat disagree",
      "Neutral",
      "Somewhat agree",
      "Agree",
      "Strongly agree"
    ),
    # selected = "Strongly agree",
    selected = ifelse(
      sum(per_data[27:32,4]) == 0, "Strongly disagree",
      as.character(per_data[27:32,][which(per_data[27:32,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Religious attendance
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_worship_attendance",
    label = "Worship service attendance:",
    choices = c(
      "Not sure",
      "Rarely attend",
      "Attend at least once a month"
    ),
    # selected = "Attend at least once a month",
    selected = ifelse(
      sum(per_data[33:34,4]) == 0, "Not sure",
      as.character(per_data[33:34,][which(per_data[33:34,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Importance of religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_religion_importance",
    label = "Importance of religion:",
    choices = c("Not important", "Important"),
    # selected = "Important",
    selected = ifelse(
      sum(per_data[35,4]) == 0, "Not important",
      as.character(per_data[35,][which(per_data[35,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Religion
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_religion",
    label = "Religion:",
    choices = c(
      'Catholic',
      'Protestant',
      'Christian Orthodox',
      'Jewish',
      'Muslim',
      'Sikh',
      'Hindu',
      'Buddhist',
      'Atheist',
      'Other religion'
    ),
    # selected = 'Protestant',
    selected = ifelse(
      sum(per_data[36:44,4]) == 0, "Catholic",
      as.character(per_data[36:44,][which(per_data[36:44,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Importance of trusting charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_charity_importance",
    label = "Charity Importance:",
    choices = c(
      "Not at all important",
      "Very unimportant",
      "Somewhat unimportant",
      "Neutral importance",
      "Somewhat important",
      "Very important",
      "Essential"
    ),
    # selected = "Somewhat unimportant",
    selected = ifelse(
      sum(per_data[45:50,4]) == 0, "Not at all important",
      as.character(per_data[45:50,][which(per_data[45:50,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Trust in charities
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_trust_in_charity",
    label = "Charity Trust:",
    choices = c(
      "No trust at all in charities",
      "Very little trust in charities",
      "Little trust in charities",
      "Neutral trust in charities",
      "Some trust in charities",
      "A lot of trust in charities",
      "Complete trust in charities"
    ),
    # selected = "Complete trust in charities",
    selected = ifelse(
      sum(per_data[51:56,4]) == 0, "No trust at all in charities",
      as.character(per_data[51:56,][which(per_data[51:56,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Donation frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_donation_frequency",
    label = "Donation Frequency:",
    choices = c('Donate more than once a month, less than once a year', 'Donate at least once a month'),
    # selected = "Donate at least once a month",
    selected = ifelse(
      sum(per_data[57,4]) == 0, "Donate more than once a month, less than once a year",
      as.character(per_data[57,][which(per_data[57,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Donated last year
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_donation_amount",
    label = "Donation Amount Last Year:",
    choices = c(
      '$1-$49',
      '$50-$99',
      '$100-$499',
      '$500-$999',
      '$1,000-$4,999',
      '$5,000-$9,999',
      '$10,000+'
    ),
    # selected = "$100-$499",
    selected = ifelse(
      sum(per_data[58:63,4]) == 0, "$1-$49",
      as.character(per_data[58:63,][which(per_data[58:63,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteered in past 12 months
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_volunteer_12",
    label = "Volunteered in last 12 Months:",
    choices = c("Haven't volunteered in past 12 months", "Volunteered in past 12 months"),
    # selected = "Volunteered in past 12 months",
    selected = ifelse(
      sum(per_data[64,4]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[64,][which(per_data[64,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Volunteer frequency
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_volunteer_frequency",
    label = "Volunteer Frequency:",
    choices = c(
      "Haven't volunteered in past 12 months",
      "Rarely volunteer",
      "Volunteer more than once a month, less than once a year",
      "Volunteer at least once a month"
    ),
    # selected = "Volunteer at least once a month",
    selected = ifelse(
      sum(per_data[65:67,4]) == 0, "Haven't volunteered in past 12 months",
      as.character(per_data[65:67,][which(per_data[65:67,4] == 1), 1])
    ),
    width = "450px"
  )
})

# History of activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_personal_activism",
    label = "Personal Activism:",
    choices = c('Not personally involved', 'Personally involved'),
    # selected = "Personally involved",
    selected = ifelse(
      sum(per_data[68,4]) == 0, "Not personally involved",
      as.character(per_data[68,][which(per_data[68,4] == 1), 1])
    ),
    width = "450px"
  )
})

# History of family activism
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_family_activism",
    label = "Family Activism:",
    choices = c('Family not involved', 'Family involved'),
    # selected = "Family involved",
    selected = ifelse(
      sum(per_data[69,4]) == 0, "Family not involved",
      as.character(per_data[69,][which(per_data[69,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Church or religious organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_religious_member",
    label = "Church Membership:",
    choices = c("Don't belong to church",'Inactive church member', 'Active church member'),
    # selected = "Don't belong to church",
    selected = ifelse(
      sum(per_data[70:71,4]) == 0, "Don't belong to church",
      as.character(per_data[70:71,][which(per_data[70:71,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Sport or recreational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_sport_member",
    label = "Sport or Recreational Membership:",
    choices = c(
      "Don't belong to sports or rec organization", 
      'Inactive sports or rec organization member',
      'Active sports or rec organization member'
    ),
    # selected = "Don't belong to sports or rec organization",
    selected = ifelse(
      sum(per_data[72:73,4]) == 0, "Don't belong to sports or rec organization",
      as.character(per_data[72:73,][which(per_data[72:73,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Art, music, or educational organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_art_member",
    label = "Art, Music, or Educational Membership:",
    choices = c(
      "Don't belong to educational organization",
      'Inactive art, music, or educational organization member',
      'Active art, music, or educational organization member'
    ),
    # selected = "Don't belong to educational organization",
    selected = ifelse(
      sum(per_data[74:75,4]) == 0, "Don't belong to educational organization",
      as.character(per_data[74:75,][which(per_data[74:75,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Labor union
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_labor_member",
    label = "Labor Union Membership:",
    choices = c("Don't belong to union", 'Inactive union member', 'Active union member'),
    # selected = "Don't belong to union",
    selected = ifelse(
      sum(per_data[76:77,4]) == 0, "Don't belong to union",
      as.character(per_data[76:77,][which(per_data[76:77,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Political party
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_political_member",
    label = "Political Party Membership:",
    choices = c(
      "Don't belong to political party",
      'Inactive political party member',
      'Active political party member'
    ),
    # selected = "Active political party member",
    selected = ifelse(
      sum(per_data[78:79,4]) == 0, "Don't belong to political party",
      as.character(per_data[78:79,][which(per_data[78:79,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Environmental organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_environmental_member",
    label = "Environmental Organization Membership:",
    choices = c(
      "Don't belong to environmental organization",
      'Inactive environmental organization member',
      'Active environmental organization member'
    ),
    # selected = "Don't belong to environmental organization",
    selected = ifelse(
      sum(per_data[80:81,4]) == 0, "Don't belong to environmental organization",
      as.character(per_data[80:81,][which(per_data[80:81,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Professional association
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_professional_member",
    label = "Professional Association Membership:",
    choices = c(
      "Don't belong to professional association",
      'Inactive professional association member',
      'Active professional association member'
    ),
    # selected = "Don't belong to professional association",
    selected = ifelse(
      sum(per_data[82:83,4]) == 0, "Don't belong to professional association",
      as.character(per_data[82:83,][which(per_data[82:83,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Humanitarian or charitable organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_humanitarian_member",
    label = "Humanitarian or Charitable Organization Membership:",
    choices = c(
      "Don't belong to humanitarian or charitable organization",
      'Inactive humanitarian or charitable organization member',
      'Active humanitarian or charitable organization member'
    ),
    # selected = "Active humanitarian or charitable organization member",
    selected = ifelse(
      sum(per_data[84:85,4]) == 0, "Don't belong to humanitarian or charitable organization",
      as.character(per_data[84:85,][which(per_data[84:85,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Consumer organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_consumer_member",
    label = "Consumer Organization Membership:",
    choices = c(
      "Don't belong to consumer organization",
      'Inactive consumer organization member',
      'Active consumer organization member'
    ),
    # selected = "Don't belong to consumer organization",
    selected = ifelse(
      sum(per_data[86:87,4]) == 0, "Don't belong to consumer organization",
      as.character(per_data[86:87,][which(per_data[86:87,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Other organization
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_other_member",
    label = "Other Organization Membership:",
    choices = c(
      "Don't belong to another organization",
      'Inactive member in another organization',
      'Active member in another organization'
    ),
    # selected = "Don't belong to another organization",
    selected = ifelse(
      sum(per_data[88:89,4]) == 0, "Don't belong to another organization",
      as.character(per_data[88:89,][which(per_data[88:89,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Gender
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_gender",
    label = "Gender:",
    choices = c(
      "Male",
      "Female",
      "Transgender",
      "Prefer not to say",
      "Other gender"
    ),
    # selected = "Female",
    selected = ifelse(
      sum(per_data[90:93,4]) == 0, "Male",
      as.character(per_data[90:93,][which(per_data[90:93,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Marital status
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_marital_status",
    label = "Marital Status:",
    choices = c(
      "Married",
      "Widowed",
      "Divorced",
      "Separated",
      "Never married"
    ),
    # selected = "Married",
    selected = ifelse(
      sum(per_data[94:97,4]) == 0, "Married",
      as.character(per_data[94:97,][which(per_data[94:97,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Education
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_education",
    label = "Education:",
    choices = c(
      "Less than high school",
      "High school graduate",
      "Some college",
      "2 year degree",
      "4 year degree",
      "Graduate or professional degree",
      "Doctorate"
    ),
    # selected = "Graduate or professional degree",
    selected = ifelse(
      sum(per_data[98:103,4]) == 0, "Less than high school",
      as.character(per_data[98:103,][which(per_data[98:103,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Income
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_income",
    label = "Income:",
    choices = c('Less than median of $61,372', 'More than median of $61,372'),
    # selected = "More than median of $61,372",
    selected = ifelse(
      sum(per_data[104,4]) == 0, "Less than median of $61,372",
      as.character(per_data[104,][which(per_data[104,4] == 1), 1])
    ),
    width = "450px"
  )
})

# Race
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_race",
    label = "Race:",
    choices = c(
      'White',
      'Black or African American',
      'American Indian or Alaskan Native',
      'Asian',
      'Native Hawaiian or Pacific Islander',
      'Other race'
    ),
    multiple = TRUE,
    # selected = c("Black or African American", "American Indian or Alaskan Native"),
    selected = deframe(per_data[105:110,][which(per_data[105:110,4] == 1), 1]),
    width = "450px"
  )
})

# Age
renderUI({
  per_data = persona_data()
  selectInput(
    "per3_age",
    label = "Age:",
    choices = c('Less than median age of 36', "More than median age of 36"),
    # selected = "Less than median age of 36",
    selected = ifelse(
      sum(per_data[111,4]) == 0, "Less than median age of 36",
      as.character(per_data[111,][which(per_data[111,4] == 1), 1])
    ),
    width = "450px"
  )
})
```

Import
-------------------------------------------------

```{r import}
# Organization configuration import
fileInput(
 "org_update",
 "Import Organization Data",
 accept = c(
   "text/csv",
   "text/comma-separated-values,text/plain",
   ".csv"
 )
)
actionButton(
 "org_button",
 label = "Update Organization Data"
)

# Persona configuration import
fileInput(
  "per_update",
  "Import Persona Data",
  accept = c(
    "text/csv",
    "text/comma-separated-values,text/plain",
    ".csv"
  )
)
actionButton(
  "per_button",
  label = "Update Persona Data"
)


# Use the default configurations if no inputs are provided
organization_data <- reactive({
  if (is.null(input$org_update$datapath)) {
    x <- org_default
  } else {
    req(input$org_button)
    req(input$org_update)
    x <- read_csv(input$org_update$datapath)
  }
})

persona_data <- reactive({
  if (is.null(input$per_update$datapath)) {
    x <- per_default
  } else {
    req(input$per_button)
    req(input$per_update)
    x <- read_csv(input$per_update$datapath)
  }
})
```

Export
--------------------------------------------------

```{r export}
# Render the organization configuration as a table
renderTable({
  org_choice = org_reactive()
  org_choice
})

# Download organization configuration
downloadButton("download_org", label = "Download Organization Data")

downloadHandler(
  filename = function() {
    paste0("org_data_",Sys.time(),".csv")
  },
  content = function(file) {
    write_csv(org_reactive(), file)
  }
)

# Render the persona configuration as a table
renderTable({
  per_choice = per_reactive()
  per_choice
})

# Download persona configuration
downloadButton("download_per", label = "Download Persona Data")

downloadHandler(
  filename = function() {
    paste0("per_data_",Sys.time(),".csv")
  },
  content = function(file) {
    write_csv(per_reactive(), file)
  }
)
```
