---
title: "Customer Credit Dashbaord"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: yeti
runtime: shiny
---

```{r setup, include=FALSE}
# Packages
library(flexdashboard)
library(shiny)
library(tidyverse)
library(ggthemes)
library(rsconnect)
library(DT)

# Data Import
customer_data <- read_csv("data/customer_data.csv") %>% 
   mutate(age = 2021 - birth_year)
```

## Sidebar {.sidebar}

This is the side bar where you can put inputs that will influence your charts

------------------------------------------------------------------------

```{r}

# Region Selection
selectInput(
  "region",
  "Region",
  choices = unique(customer_data[,8])
)

# # State Selection
# selectInput(
#   "state",
#   "State",
#   choices = unique(customer_data[,9]),
#   selected = "UT"
# )

# # Marital Status Selection
# selectInput(
#   "marital",
#   "Marital Status",
#   choices = c("Yes", "No"),
#   selected = "Yes"
# )

# # College Degree Selection
# selectInput(
#   "college",
#   "College Degree",
#   choices = c("Yes", "No"),
#   selected = "Yes"
# )

sliderInput(
  "age",
  "Age Range",
  min = min(customer_data$age),
  max = max(customer_data$age),
  value = c(min(customer_data$age), max(customer_data$age))
)
```

Row
------------------------------------------------------------------------

### Age versus Credit

```{r}
renderPlot({
  customer_data %>% 
    filter(region == input$region) %>% 
    ggplot(aes(x = age, y = credit, size = income, color = gender, alpha = 0.2)) +
    geom_jitter() +
    xlim(input$age[1], input$age[2]) +
    # geom_smooth(method = "lm", se = FALSE) +
    theme_minimal()
})


```

Row
------------------------------------------------------------------------

<!-- ### Summary Table -->

<!-- ```{r} -->
<!-- DT::renderDataTable({ -->
<!--   customer_data %>%  -->
<!--     group_by(region) %>%  -->
<!--     summarize( -->
<!--       ave_credit = round(mean(credit), 1), -->
<!--       ave_income = round(mean(income), 1), -->
<!--       ave_age = round(mean(age),0) -->
<!--     ) -->
<!-- }) -->



<!-- ``` -->

### Average Income

```{r}

summary <- reactive({

})

renderValueBox({
  summary <- customer_data %>% 
    filter(region == input$region)
  
  valueBox(round(mean(summary$income),0), icon = "fa-money")
})



```

### Average Credit Score

```{r}

summary <- reactive({

})

renderValueBox({
  summary <- customer_data %>% 
    filter(region == input$region)
  
  valueBox(round(mean(summary$credit),0), icon = "fa-bank")
})



```

### Median Age

```{r}

summary <- reactive({

})

renderValueBox({
  summary <- customer_data %>% 
    filter(region == input$region)
  
  valueBox(median(summary$age), icon = "fa-address-book")
})



```
