---
title: "Market simulator"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
runtime: shiny
---

Look at this link to figure out `fillCol()` and `fillRow()` [here](https://stackoverflow.com/questions/36451484/how-to-combine-row-and-column-layout-in-flexdashboard)


```{r load-packages, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(flexdashboard)
library(plotly)
library(shiny)
```

```{r load-data, message=FALSE}

# If we simplify any of the default data sets make sure it matches the gammas as well.

# number of Gamma rows -> number of Organization rows

# number of Gamma Cols -> number of segment Rows


# Gammas of the "everything" model
gammas <- read_rds(
    here::here('data', 'public_political_social_charity_demo.rds')
  ) %>% 
  group_by(i, j) %>% 
  summarize(gamma_mean = mean(Gamma)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = j, values_from = gamma_mean) %>% 
  select(-i) %>% 
  t()

gammas <- gammas[,1:12]
  

# Default configurations
prod_default <- read_csv(
    here::here('data', 'org_data_default.csv')
  ) %>% 
  mutate(
    levels = c(
      # Brand
      "Hydroflask",
      "Conmigo",
      "Nalgene",
      "Camelbak",
      # Lid Type default = Screwcap
      "Wide Mouth", 
      "Squeeze",
      "Straw",
      # Size default = 24 oz
      "36 oz",
      # Material default = plastic
      "Metal",
      # Color Default = Clear 
      "Red", 
      "Blue",
      # Price Default = $19.99
      "$24.99",
      "$29.99"
    )
  ) %>% 
  rename(
    prod1_value = org1_value,
    prod2_value = org2_value,
    prod3_value = org3_value,
    prod4_value = org4_value 
  )

seg_default <- read_csv(
    here::here('data', 'per_data_default.csv')
  ) %>% 
  head(., 12)
```

```{r product-reactive-table}
# Assign level labels
prod_table <- data.frame(
  levels = c(
    # Brand
    "Hydroflask",
    "Conmigo",
    "Nalgene",
    "Camelbak",
    # Lid Type default = Screwcap
    "Wide Mouth", 
    "Squeeze",
    "Straw",
    # Size default = 24 oz
    "36 oz",
    # Material default = plastic
    "Metal",
    # Color Default = Clear 
    "Red", 
    "Blue",
    # Price Default = $19.99
    "$24.99",
    "$29.99"
  )
)

# Product configuration reactive element
prod_reactive <- reactive({
  # Product 1
  prod_table$prod1_value <- 0
  prod_table$prod1_value[prod_table$levels %in% input$prod1_prod] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_issue] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_fin_trans] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_fin_account] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_funding] <- 1
  prod_table$prod1_value[prod_table$levels %in% input$prod1_host_gov] <- 1
    
  # Product 2
  prod_table$prod2_value <- 0
  prod_table$prod2_value[prod_table$levels %in% input$prod2_prod] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_issue] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_fin_trans] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_fin_account] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_funding] <- 1
  prod_table$prod2_value[prod_table$levels %in% input$prod2_host_gov] <- 1
    
  # Product 3
  prod_table$prod3_value <- 0
  prod_table$prod3_value[prod_table$levels %in% input$prod3_prod] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_issue] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_fin_trans] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_fin_account] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_funding] <- 1
  prod_table$prod3_value[prod_table$levels %in% input$prod3_host_gov] <- 1
    
  # Product 4
  prod_table$prod4_value <- 0
  prod_table$prod4_value[prod_table$levels %in% input$prod4_prod] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_issue] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_fin_trans] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_fin_account] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_funding] <- 1
  prod_table$prod4_value[prod_table$levels %in% input$prod4_host_gov] <- 1
  prod_table
})
```

```{r segment-reactive-table}
# Assign covariate labels
seg_table <- data.frame(
  levels = c(
    # Intercept
    "Intercept",
    # Follow national news
    "Once a week",
    "At least once a day",
    # Follow international news
    "Sometimes",
    "Always",
    # Mediums to follow news
    "TV",
    "Print",
    "Online (not social media)",
    "Social media",
    "Radio",
    "Email newsletter",
    "News app"
  )
)

# Segment configuration reactive element
seg_reactive <- reactive({
  # Segment 1
  seg_table$seg1_value <- 0
  seg_table$seg1_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$seg1_national_news] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$seg1_international_news] <- 1
  seg_table$seg1_value[seg_table$levels %in% input$seg1_news_medium] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_follow_gov] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_travel_developing] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_political_pref] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_institution_trust] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_others_charitable] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_worship_attendance] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_religion_importance] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_religion] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_charity_importance] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_trust_in_charity] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_donation_frequency] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_donation_amount] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_volunteer_12] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_volunteer_frequency] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_personal_activism] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_family_activism] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_religious_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_sport_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_art_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_labor_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_political_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_environmental_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_professional_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_humanitarian_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_consumer_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_other_member] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_gender] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_marital_status] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_education] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_income] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_race] <- 1
  # seg_table$seg1_value[seg_table$levels %in% input$seg1_age] <- 1
    
  # Segment 2
  seg_table$seg2_value <- 0
  seg_table$seg2_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$seg2_national_news] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$seg2_international_news] <- 1
  seg_table$seg2_value[seg_table$levels %in% input$seg2_news_medium] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_follow_gov] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_travel_developing] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_political_pref] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_institution_trust] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_others_charitable] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_worship_attendance] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_religion_importance] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_religion] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_charity_importance] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_trust_in_charity] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_donation_frequency] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_donation_amount] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_volunteer_12] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_volunteer_frequency] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_personal_activism] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_family_activism] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_religious_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_sport_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_art_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_labor_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_political_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_environmental_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_professional_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_humanitarian_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_consumer_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_other_member] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_gender] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_marital_status] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_education] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_income] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_race] <- 1
  # seg_table$seg2_value[seg_table$levels %in% input$seg2_age] <- 1
    
  # Segment 3
  seg_table$seg3_value <- 0
  seg_table$seg3_value[seg_table$levels == 'Intercept'] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$seg3_national_news] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$seg3_international_news] <- 1
  seg_table$seg3_value[seg_table$levels %in% input$seg3_news_medium] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_follow_gov] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_travel_developing] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_political_pref] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_institution_trust] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_others_charitable] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_worship_attendance] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_religion_importance] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_religion] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_charity_importance] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_trust_in_charity] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_donation_frequency] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_donation_amount] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_volunteer_12] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_volunteer_frequency] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_personal_activism] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_family_activism] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_religious_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_sport_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_art_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_labor_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_political_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_environmental_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_professional_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_humanitarian_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_consumer_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_other_member] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_gender] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_marital_status] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_education] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_income] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_race] <- 1
  # seg_table$seg3_value[seg_table$levels %in% input$seg3_age] <- 1
  seg_table
})
```

Market share
====================================================

Plot
-------------------------------------------------

### Product Market Share Per Segment

```{r compute-and-plot}
# Compute and render the market share plot
renderPlotly({
  prod_choice = prod_reactive()
  seg_choice = seg_reactive()
    
  # Segment 1 predicted betas
  seg1_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,2])
  
  # Segment 1 expected utilities
  seg1_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg1_betas))
  seg1_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg1_betas))
  seg1_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg1_betas))
  seg1_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg1_betas))
  
  # Segment 1 market shares
  seg1_share_denom <- sum(seg1_prod1_exp, seg1_prod2_exp, seg1_prod3_exp, seg1_prod4_exp)
  seg1_prod1_share <- 100 * (seg1_prod1_exp / seg1_share_denom)
  seg1_prod2_share <- 100 * (seg1_prod2_exp / seg1_share_denom)
  seg1_prod3_share <- 100 * (seg1_prod3_exp / seg1_share_denom)
  seg1_prod4_share <- 100 * (seg1_prod4_exp / seg1_share_denom)
  
  # Segment 2 predicted betas
  seg2_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,3])
  
  # Segment 2 expected utilities
  seg2_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg2_betas))
  seg2_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg2_betas))
  seg2_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg2_betas))
  seg2_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg2_betas))
  
  # Segment 2 market shares
  seg2_share_denom <- sum(seg2_prod1_exp, seg2_prod2_exp, seg2_prod3_exp, seg2_prod4_exp)
  seg2_prod1_share <- 100 * (seg2_prod1_exp / seg2_share_denom)
  seg2_prod2_share <- 100 * (seg2_prod2_exp / seg2_share_denom)
  seg2_prod3_share <- 100 * (seg2_prod3_exp / seg2_share_denom)
  seg2_prod4_share <- 100 * (seg2_prod4_exp / seg2_share_denom)
  
  # Segment 3 predicted betas
  seg3_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,4])
  
  # Segment 3 expected utilities
  seg3_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg3_betas))
  seg3_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg3_betas))
  seg3_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg3_betas))
  seg3_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg3_betas))
  
  # Segment 3 market shares
  seg3_share_denom <- sum(seg3_prod1_exp, seg3_prod2_exp, seg3_prod3_exp, seg3_prod4_exp)
  seg3_prod1_share <- 100 * (seg3_prod1_exp / seg3_share_denom)
  seg3_prod2_share <- 100 * (seg3_prod2_exp / seg3_share_denom)
  seg3_prod3_share <- 100 * (seg3_prod3_exp / seg3_share_denom)
  seg3_prod4_share <- 100 * (seg3_prod4_exp / seg3_share_denom)
  
  # Data for plotly
  plot_data <- data.frame(
    Value = c(
      # Segment 1
      seg1_prod1_share, seg1_prod2_share, seg1_prod3_share, seg1_prod4_share, 
      # Segment 2
      seg2_prod1_share, seg2_prod2_share, seg2_prod3_share, seg2_prod4_share,
      # Segment 3
      seg3_prod1_share, seg3_prod2_share, seg3_prod3_share, seg3_prod4_share
    ),
    Product = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name),
    Segment = c(
      rep(input$seg1_name, 4), 
      rep(input$seg2_name, 4), 
      rep(input$seg3_name, 4)
    )
  )
  
  ggplotly(
    plot_data %>% 
      # Factor Product and Segment with ordered=TRUE
      mutate(
        Product = factor(
          Product, 
          levels = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name), 
          ordered = TRUE
        ),
        Segment = factor(
          Segment, 
          levels = c(input$seg1_name, input$seg2_name, input$seg3_name), 
          ordered = TRUE
        )
      ) %>% 
      ggplot(aes(y = Value, x = Product, fill = Segment)) +
      geom_bar(position = "dodge", stat = "identity") +
      labs(x="", y = "Market Share") + 
      scale_fill_manual(values = c("#FFC30B", "#28a153", "#c23838")) +
      theme(
        legend.position = "right",
        panel.background = element_blank(),
        panel.grid.major.y = element_line(color = "#D3D3D3")
      )
    )
})

# Compute and render the market share as a table
# renderTable({
#   prod_choice = prod_reactive()
#   seg_choice = seg_reactive()
#     
#   # Segment 1 predicted betas
#   seg1_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,2])
#   
#   # Segment 1 expected utilities
#   seg1_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg1_betas))
#   seg1_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg1_betas))
#   seg1_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg1_betas))
#   seg1_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg1_betas))
#   
#   # Segment 1 market shares
#   seg1_share_denom <- sum(seg1_prod1_exp, seg1_prod2_exp, seg1_prod3_exp, seg1_prod4_exp)
#   seg1_prod1_share <- 100 * (seg1_prod1_exp / seg1_share_denom)
#   seg1_prod2_share <- 100 * (seg1_prod2_exp / seg1_share_denom)
#   seg1_prod3_share <- 100 * (seg1_prod3_exp / seg1_share_denom)
#   seg1_prod4_share <- 100 * (seg1_prod4_exp / seg1_share_denom)
#   
#   # Segment 2 predicted betas
#   seg2_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,3])
#   
#   # Segment 2 expected utilities
#   seg2_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg2_betas))
#   seg2_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg2_betas))
#   seg2_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg2_betas))
#   seg2_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg2_betas))
#   
#   # Segment 2 market shares
#   seg2_share_denom <- sum(seg2_prod1_exp, seg2_prod2_exp, seg2_prod3_exp, seg2_prod4_exp)
#   seg2_prod1_share <- 100 * (seg2_prod1_exp / seg2_share_denom)
#   seg2_prod2_share <- 100 * (seg2_prod2_exp / seg2_share_denom)
#   seg2_prod3_share <- 100 * (seg2_prod3_exp / seg2_share_denom)
#   seg2_prod4_share <- 100 * (seg2_prod4_exp / seg2_share_denom)
#   
#   # Segment 3 predicted betas
#   seg3_betas <- as.matrix(gammas) %*% as.matrix(seg_choice[,4])
#   
#   # Segment 3 expected utilities
#   seg3_prod1_exp <- exp(t(prod_choice[,2]) %*% as.matrix(seg3_betas))
#   seg3_prod2_exp <- exp(t(prod_choice[,3]) %*% as.matrix(seg3_betas))
#   seg3_prod3_exp <- exp(t(prod_choice[,4]) %*% as.matrix(seg3_betas))
#   seg3_prod4_exp <- exp(t(prod_choice[,5]) %*% as.matrix(seg3_betas))
#   
#   # Segment 3 market shares
#   seg3_share_denom <- sum(seg3_prod1_exp, seg3_prod2_exp, seg3_prod3_exp, seg3_prod4_exp)
#   seg3_prod1_share <- 100 * (seg3_prod1_exp / seg3_share_denom)
#   seg3_prod2_share <- 100 * (seg3_prod2_exp / seg3_share_denom)
#   seg3_prod3_share <- 100 * (seg3_prod3_exp / seg3_share_denom)
#   seg3_prod4_share <- 100 * (seg3_prod4_exp / seg3_share_denom)
#   
#   # Table
#   data <- data.frame(
#     Shares = c(
#       # Segment 1
#       seg1_prod1_share, seg1_prod2_share, seg1_prod3_share, seg1_prod4_share, 
#       # Segment 2
#       seg2_prod1_share, seg2_prod2_share, seg2_prod3_share, seg2_prod4_share,
#       # Segment 3
#       seg3_prod1_share, seg3_prod2_share, seg3_prod3_share, seg3_prod4_share
#     ),
#     Product = c(input$prod1_name, input$prod2_name, input$prod3_name, input$prod4_name),
#     Segment = c(
#       rep(input$seg1_name, 4), 
#       rep(input$seg2_name, 4), 
#       rep(input$seg3_name, 4)
#     )
#   ) %>% 
#     pivot_wider(names_from = Segment, values_from = Shares)
#   
#   data
# })
```

Product Configurations
-------------------------------------------------

```{r prod1-inputs}
# Naming
textInput(
  "prod1_name",
  label = "Product Name:",
  value = "Product 1",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Brand
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_prod",
    label = "Brand:",
    choice = c("Hydroflask", "Conmigo", "Nalgene", "Camelbak"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,2] == 1), 1]),
    width = "450px"
  )
})

# Lid Type
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_issue", 
    label = "Lid Type:",
    choices = c("Screwlid", "Wide Mouth", "Squeeze", "Straw"),
    # selected = "Emergency response",
    selected = ifelse(
      sum(prod_data[5:7,2]) == 0, "Screwlid",
      as.character(prod_data[5:7,][which(prod_data[5:7,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Size
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_fin_trans",
    label = "Size:",
    choices = c(
      "24 oz",
      "36 oz"
    ),
    # selected = "24 oz",
    selected = ifelse(
      sum(prod_data[8,2]) == 0, "24 oz",
      as.character(prod_data[8,][which(prod_data[8,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Material
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_fin_account",
    label = "Material:",
    choices = c(
      "Plastic",
      "Metal"
    ),
    # selected = "Plastic",
    selected = ifelse(
      sum(prod_data[9,2]) == 0, "Plastic",
      as.character(prod_data[9,][which(prod_data[9,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Color
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_funding",
    label = "Color:",
    choices = c(
      "Clear",
      "Red",
      "Blue"
    ),
    # selected = "Clear",
    selected = ifelse(
      sum(prod_data[10:11,2]) == 0, "Clear",
      as.character(prod_data[10:11,][which(prod_data[10:11,2] == 1), 1])
    ),
    width = "450px"
  )
})

# Price
renderUI({
  prod_data = product_data()
  selectInput(
    "prod1_host_gov",
    label = "Price:",
    choices = c(
      "$19.99",
      "$24.99",
      "$29.99"
    ),
    # selected = "$19.99",
    selected = ifelse(
      sum(prod_data[12:13,2]) == 0, "$19.99",
      as.character(prod_data[12:13,][which(prod_data[12:13,2] == 1), 1])
    ),
    width = "450px"
  )
})
```

```{r prod2-inputs}
# Naming
textInput(
  "org2_name",
  label = "Product Name:",
  value = "Product 2",
  placeholder = "Enter Product Name",
  width = "450px"
)

# Product
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_prod",
    label = "Product:",
    choice = c("Hydroflask", "Conmigo", "Nalgene", "Camelbak"),
    # selected = "Red Cross",
    selected = as.character(prod_data[1:4,][which(prod_data[1:4,3] == 1), 1]),
    width = "450px"
  )
})

# Issue area
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_issue", 
    label = "Issue Area:",
    choices = c("Emergency response", "Environment", "Human rights", "Refugee relief"),
    # selected = "Environment",
    selected = ifelse(
      sum(prod_data[5:7,3]) == 0, "Emergency response",
      as.character(prod_data[5:7,][which(prod_data[5:7,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial transparency
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_fin_trans",
    label = "Financial Transparency:",
    choices = c(
      "Doesn’t engage in financial transparency", 
      "Engages in financial transparency"
    ),
    # selected = "Engages in financial transparency",
    selected = ifelse(
      sum(prod_data[8,3]) == 0, "Doesn’t engage in financial transparency",
      as.character(prod_data[8,][which(prod_data[8,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Financial accountability
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_fin_account",
    label = "Financial Accountability:",
    choices = c(
      "Doesn’t engage in financial accountability", 
      "Engages in financial accountability"
    ),
    # selected = "Engages in financial accountability",
    selected = ifelse(
      sum(prod_data[9,3]) == 0, "Doesn’t engage in financial accountability",
      as.character(prod_data[9,][which(prod_data[9,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Funding sources
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_funding",
    label = "Funding Source:",
    choices = c(
      "Many small private donations", 
      "Handful of wealthy private donors", 
      "Government grants"
    ),
    # selected = "Many small private donations",
    selected = ifelse(
      sum(prod_data[10:11,3]) == 0, "Many small private donations",
      as.character(prod_data[10:11,][which(prod_data[10:11,3] == 1), 1])
    ),
    width = "450px"
  )
})

# Relationship with host government
renderUI({
  prod_data = product_data()
  selectInput(
    "prod2_host_gov",
    label = "Relationship With Host Government",
    choices = c(
      "Friendly relationship with government", 
      "Criticized by government",  
      "Under government crackdown"
    ),
    # selected = "Friendly relationship with government",
    selected = ifelse(
      sum(prod_data[12:13,3]) == 0, "Friendly relationship with government",
      as.character(prod_data[12:13,][which(prod_data[12:13,3] == 1), 1])
    ),
    width = "450px"
  )
})
```

Import & Export
====================================================

```{r import}
# Organization configuration import
fileInput(
 "prod_update",
 "Import Product Data",
 accept = c(
   "text/csv",
   "text/comma-separated-values,text/plain",
   ".csv"
 )
)
actionButton(
 "prod_button",
 label = "Update Product Data"
)

# segment configuration import
fileInput(
  "seg_update",
  "Import segment Data",
  accept = c(
    "text/csv",
    "text/comma-separated-values,text/plain",
    ".csv"
  )
)
actionButton(
  "seg_button",
  label = "Update segment Data"
)


# Use the default configurations if no inputs are provided
product_data <- reactive({
  if (is.null(input$prod_update$datapath)) {
    x <- prod_default
  } else {
    req(input$prod_button)
    req(input$prod_update)
    x <- read_csv(input$prod_update$datapath)
  }
})

segment_data <- reactive({
  if (is.null(input$seg_update$datapath)) {
    x <- seg_default
  } else {
    req(input$seg_button)
    req(input$seg_update)
    x <- read_csv(input$seg_update$datapath)
  }
})
```

```{r export}
# Render the organization configuration as a table
renderTable({
  prod_choice = prod_reactive()
  prod_choice
})

# Download organization configuration
downloadButton("download_prod", label = "Download Product Data")

downloadHandler(
  filename = function() {
    paste0("prod_data_",Sys.time(),".csv")
  },
  content = function(file) {
    write_csv(prod_reactive(), file)
  }
)

# Render the segment configuration as a table
renderTable({
  seg_choice = seg_reactive()
  seg_choice
})

# Download segment configuration
downloadButton("download_seg", label = "Download segment Data")

downloadHandler(
  filename = function() {
    paste0("seg_data_",Sys.time(),".csv")
  },
  content = function(file) {
    write_csv(seg_reactive(), file)
  }
)
```


